### ISSUE TITLE
How to use configmap for sampling strategies

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-kubernetes#100]
See https://github.com/jaegertracing/jaeger/issues/970 
cc @Yisaer

**Comment by Yisaer** [comment]
thanks.  @pavolloffay

**Comment by pavolloffay** [comment]
Here is an example how you can use configmap with jaeger all-in-one https://github.com/pavolloffay/jaeger-kubernetes/commit/1343b07d6a1a302fb6eb9532aebe74f44a4404d5

```bash
/ # ls /etc/
conf         hostname     hosts        jaeger       mtab         resolv.conf
/ # 
/ # ls /etc/conf/
config.json
/ # ls /etc/conf/config.json 
/etc/conf/config.json
/ # cat  /etc/conf/config.json 
{
  "service_strategies": [
    {
      "service": "istio-mixer",
      "type": "probabilistic",
      "param": 0
    },
    {
      "service": "istio-policy",
      "type": "probabilistic",
      "param": 0
    },
    {
        "service": "istio-telemetry",
        "type": "probabilistic",
        "param": 0
    }
  ],
  "default_strategy": {
    "type": "probabilistic",
    "param": 1
  }
}   / # 
/ # 
/ # exit
```

**Comment by pavolloffay** [comment]
The settings looks very or maybe the same as in your config. You can ssh into the container and see if the file is there. Note that we use from cratch you will need something like this https://github.com/kubernetes/contrib/tree/master/scratch-debugger (I had to also add https://github.com/kubernetes/contrib/pull/2904)

**Comment by Yisaer** [comment]
I found that it only works in `all-in-one` version 1.6, but sampling.strategies doesn't work.
https://github.com/jaegertracing/jaeger-kubernetes/issues/101

**Comment by naseemkullah** [comment]
In case you are using helm (another CNCF project) once this is merged you can use it https://github.com/helm/charts/pull/19277/files

**Comment by pavolloffay** [comment]
I am closing this one please use the operator to configure config jaeger in k8s.
