### ISSUE TITLE
Error reading service_names from storage: Cannot achieve consistency level LOCAL_ONE

### ISSUE THREAD

**Issue by sneko** [jaegertracing/jaeger-kubernetes#102]
Hi!

I just created a Cassandra cluster with an operator (https://github.com/instaclustr/cassandra-operator) and the Cassandra schema job succeeded but when going to the Jaeger Query UI I get the following error:
```
{   "data": null,   "total": 0,   "limit": 0,   "offset": 0,   "errors": [     {       "code": 500,       "msg": "Error reading service_names from storage: Cannot achieve consistency level LOCAL_ONE"     }   ] }
--
```

I also get this error in the Jaeger Collector logs.

I saw this error in the following issue that seems related:
https://github.com/jaegertracing/jaeger/issues/513

But when adding the specified env variables to the CustomResourceDefiniton of the Cassandra cluster they don't seem to be propagated to the cassandra pod but just to it's sidecar (since they still are in alpha it may be an issue on their side).

I tried to add them manually to the statefulset and restart the cassandra pods but it doesn't work. It looks like the operator override these changes quickly (need more time to confirm).

While I'm trying to figure out how to set these variables without troubles with the operator, does anyone already see this error and resolved it by another way? Since the error is not that much explicit I'm wondering if it comes from here.

Thanks

**Comment by jpkrohling** [comment]
I'm not sure we can be of much help here. What we can suggest is to use the Cassandra template we provide in this repository and see if that works in your environment. If it does, then you might want to get help from the operator providers.

https://github.com/jaegertracing/jaeger-kubernetes#backing-storage

**Comment by pavolloffay** [comment]
@sneko it looks like a C* configuration issue. https://github.com/jaegertracing/jaeger/issues/513#issuecomment-344275159 this might help you.

**Comment by sneko** [comment]
@jpkrohling I tried to provision a C* datastore with your Helm chart but I get the following error:
```Error: release jaeger failed: StatefulSet.apps "jaeger-cassandra" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"cassandra", "release":"jaeger"}: `selector` does not match template `labels`]```

I looked into charts code but I can't figure out where the wrong value is set. FYI I'm using the default values.yaml (https://github.com/helm/charts/blob/master/incubator/jaeger/values.yaml).

Is it the same on your side?

@pavolloffay yeah that's the issue I mentioned but when providing env variables the Cassandra operator doesn't spread them to the C* nodes. Maintainers are on it :)

**Comment by jpkrohling** [comment]
@sneko the Helm chart is hosted under a different repository. I could try to help you debug it, but it would be better to open an issue there, as I'm not really familiar with its storage setup.

This is the Helm chart repository: https://github.com/helm/charts/tree/master/incubator/jaeger

**Comment by sneko** [comment]
@jpkrohling just posted the issue:
https://github.com/helm/charts/issues/7407

I close this one since while talking with the C* operator team they told me there could be some issues due to their custom C* image:
https://github.com/instaclustr/cassandra-operator/issues/82#issuecomment-416299477

Thanks for all your answers 😀

**Comment by sneko** [comment]
@jpkrohling someone else thumbed up my issue on the Helm chart repository, it seems I'm not the only one 😀... Did you have time to dig into it?

Thank you,

**Comment by jpkrohling** [comment]
I haven't, I've been focused on the [Jaeger Operator](https://github.com/jaegertracing/jaeger-kubernetes) for the last week, but I'm still not sure what I could do to help you there other than ping some people more knowledgeable about the Helm chart.
