### ISSUE TITLE
Docker for Windows with Kubernetes (all-in-one) jaeger not working

### ISSUE THREAD

**Issue by kargencW** [jaegertracing/jaeger-kubernetes#118]
kubernetes pod has a failed connect message while starting like

```
{"level":"info","ts":1561379210.7517905,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {127.0.0.1:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:14250: connect: connection refused\". Reconnecting...","system":"grpc","grpc_log":true}
```

 my c# client api can't send a trace, with kubernetes(all-in-one),  haven't any problem with 
```
docker run -d --name jaeger -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 -p 5775:5775/udp -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778 -p 16686:16686 -p 14268:14268 -p 9411:9411 jaegertracing/all-in-one:latest
```

My deployment description is 
```
Name:               jaeger
Namespace:          default
CreationTimestamp:  Mon, 24 Jun 2019 15:26:47 +0300
Labels:             app=jaeger
                    app.kubernetes.io/component=all-in-one
                    app.kubernetes.io/name=jaeger
Annotations:        deployment.kubernetes.io/revision=1
Selector:           app=jaeger,app.kubernetes.io/component=all-in-one,app.kubernetes.io/name=jaeger
Replicas:           1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:       Recreate
MinReadySeconds:    0
Pod Template:
  Labels:       app=jaeger
                app.kubernetes.io/component=all-in-one
                app.kubernetes.io/name=jaeger
  Annotations:  prometheus.io/port=16686
                prometheus.io/scrape=true
  Containers:
   jaeger:
    Image:       jaegertracing/all-in-one
    Ports:       5775/UDP, 6831/UDP, 6832/UDP, 5778/TCP, 16686/TCP, 9411/TCP
    Host Ports:  0/UDP, 0/UDP, 0/UDP, 0/TCP, 0/TCP, 0/TCP
    Readiness:   http-get http://:14269/ delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      COLLECTOR_ZIPKIN_HTTP_PORT:  9411
    Mounts:                        <none>
  Volumes:                         <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   jaeger-796dcb98cb (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  5m    deployment-controller  Scaled up replica set jaeger-796dcb98cb to 1
```

**Comment by jpkrohling** [comment]
How are you creating your deployment? Are you using the Kubernetes template? Apparently, you are not exposing the gRPC port `14250`.

**Comment by jpkrohling** [comment]
Could you please try to add the port `14250` to this list of ports:

https://github.com/jaegertracing/jaeger-kubernetes/blob/bcca10c297b38c01d9d7c554172572ffa11944ce/all-in-one/jaeger-all-in-one-template.yml#L46-L58

If it works, it would be great if you could send a PR fixing that, as well as the production template:

https://github.com/jaegertracing/jaeger-kubernetes/blob/bcca10c297b38c01d9d7c554172572ffa11944ce/jaeger-production-template.yml#L44-L50

**Comment by kargencW** [comment]
thnk u very quick response, is 14250 TCP port?

**Comment by jpkrohling** [comment]
Yes, it's a TCP port.

**Comment by kargencW** [comment]
>               ports:
                - containerPort: 5775
                  protocol: UDP
                - containerPort: 6831
                  protocol: UDP
                - containerPort: 6832
                  protocol: UDP
                - containerPort: 5778
                  protocol: TCP
                - containerPort: 16686
                  protocol: TCP
                - containerPort: 9411
                  protocol: TCP
                - containerPort: 14250
                  protocol: TCP
i added 14250 TCP but i get 

`{"level":"info","ts":1561384398.8092573,"caller":"flags/service.go:115","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1561384398.8094695,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1561384398.8095016,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14269}
{"level":"info","ts":1561384398.8095126,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14269,"health-status":"unavailable"}
{"level":"info","ts":1561384398.816948,"caller":"memory/factory.go:55","msg":"Memory storage initialized","configuration":{"MaxTraces":0}}
{"level":"info","ts":1561384398.8199265,"caller":"grpc/builder.go:75","msg":"Agent requested insecure grpc connection to collector(s)"}
{"level":"info","ts":1561384398.8207796,"caller":"grpc/clientconn.go:242","msg":"parsed scheme: \"\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1561384398.825003,"caller":"grpc/clientconn.go:248","msg":"scheme \"\" not registered, fallback to default scheme","system":"grpc","grpc_log":true}
{"level":"info","ts":1561384398.825185,"caller":"grpc/resolver_conn_wrapper.go:113","msg":"ccResolverWrapper: sending update to cc: {[{127.0.0.1:14250 0  <nil>}] }","system":"grpc","grpc_log":true}
{"level":"info","ts":1561384398.8294165,"caller":"base/balancer.go:76","msg":"base.baseBalancer: got new resolver state: {[{127.0.0.1:14250 0  <nil>}] }","system":"grpc","grpc_log":true}
{"level":"info","ts":1561384398.8295877,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0000472e0, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1561384398.8300455,"caller":"all-in-one/main.go:198","msg":"Starting agent"}
{"level":"info","ts":1561384398.8408072,"caller":"app/agent.go:68","msg":"Starting jaeger-agent HTTP server","http-port":5778}

> {"level":"info","ts":1561384398.8410192,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {127.0.0.1:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:14250: connect: connection refused\". Reconnecting...","system":"grpc","grpc_log":true}
> {"level":"info","ts":1561384398.8410945,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0000472e0, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}

{"level":"info","ts":1561384398.8487308,"caller":"all-in-one/main.go:241","msg":"Starting jaeger-collector TChannel server","port":14267}
{"level":"info","ts":1561384398.8488111,"caller":"grpcserver/grpc_server.go:64","msg":"Starting jaeger-collector gRPC server","grpc-port":"14250"}
{"level":"info","ts":1561384398.8488743,"caller":"all-in-one/main.go:259","msg":"Starting jaeger-collector HTTP server","http-port":14268}
{"level":"info","ts":1561384398.848887,"caller":"querysvc/query_service.go:130","msg":"Archive storage not created","reason":"archive storage not supported"}
{"level":"info","ts":1561384398.8497703,"caller":"all-in-one/main.go:341","msg":"Archive storage not initialized"}
{"level":"info","ts":1561384398.8501568,"caller":"healthcheck/handler.go:129","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1561384398.8501797,"caller":"app/server.go:131","msg":"Starting CMUX server","port":16686}
{"level":"info","ts":1561384398.8502288,"caller":"app/server.go:108","msg":"Starting HTTP server","port":16686}
{"level":"info","ts":1561384398.85024,"caller":"app/server.go:121","msg":"Starting GRPC server","port":16686}
{"level":"info","ts":1561384398.8673692,"caller":"all-in-one/main.go:297","msg":"Listening for Zipkin HTTP traffic","zipkin.http-port":9411}`

**Comment by jpkrohling** [comment]
It actually looks alright:

```
{"level":"info","ts":1561384398.8501568,"caller":"healthcheck/handler.go:129","msg":"Health Check state change","status":"ready"}
```

Are you seeing errors in the client?

**Comment by kargencW** [comment]
`info: Jaeger.Configuration[0]
      Initialized Tracer(ServiceName=hello - world, Version=CSharp-0.3.2.0, Reporter=CompositeReporter(Reporters=RemoteReporter(Sender=UdpSender(UdpTransport=ThriftUdpClientTransport(Client=127.0.0.1:6831))), LoggingReporter(Logger=Microsoft.Extensions.Logging.Logger`1[Jaeger.Reporters.LoggingReporter])), Sampler=ConstSampler(True), IPv4=167791361, Tags=[jaeger.version, CSharp-0.3.2.0], [hostname, DESKTOP-2JD0BQ0], [ip, 10.0.75.1], ZipkinSharedRpcSpan=False, ExpandExceptionLogs=False, UseTraceId128Bit=False)
Doing some heavy stuff.
Doing some heavy stuff.
Doing some heavy stuff.
Doing some heavy stuff.
Doing some heavy stuff.
info: Jaeger.Reporters.LoggingReporter[0]
      Span reported: 1810c08d1a8b0aa0:1810c08d1a8b0aa0:0:1 - someWork`


it doesn't give any error, it shows sent, but I don't see anything from the interface, there is also a no transfer log in the kubernetes logs.

**Comment by jpkrohling** [comment]
Are you deploying the agent as a sidecar to your application's `Deployment`? Your logs are showing that spans are being sent to `127.0.0.1`, implying that you either are using a sidecar, or missing the agent's hostname. See the README's section [Jaeger components](https://github.com/jaegertracing/jaeger-kubernetes#jaeger-components) and the one right after that, [Deploying the agent as sidecar](https://github.com/jaegertracing/jaeger-kubernetes#deploying-the-agent-as-sidecar).

If you are using a sidecar, please paste the logs from the sidecar.

It might also be worth taking a look at the troubleshooting guide: https://www.jaegertracing.io/docs/1.12/troubleshooting/

**Comment by kargencW** [comment]
when i run docker with this command and same client app working well 
`docker run -d --name jaeger -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 -p 5775:5775/udp -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778 -p 16686:16686 -p 14268:14268 -p 9411:9411 jaegertracing/all-in-one:latest`
but with kubernates, same client app seems send trace in logs but actually not
`kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-kubernetes/master/all-in-one/jaeger-all-in-one-template.yml`

**Comment by jpkrohling** [comment]
Your Docker command is executed at your main host and exposes a port to `localhost`. Kubernetes is in a totally different network, and your application's pod isn't in the `localhost` of Jaeger's pod. Please, refer to the README for details on how to set the agent's hostname.

I'm closing this, as it's clear that it's a networking setting in your setup.
