### ISSUE TITLE
Not support elasticsearch 6.0+

### ISSUE THREAD

**Issue by vx610sky** [jaegertracing/jaeger-kubernetes#129]
## Any open questions to address

![image](https://user-images.githubusercontent.com/17560081/75440688-31e13d00-5997-11ea-99fd-2bb1a6c8c212.png)

**Comment by pavolloffay** [comment]
Jaeger supports all ES version: 5x, 6x and 7x. Try to upgrade Jaeger. If the issue will be still present open it in the main repository with full jaeger logs and Jaeger configuration.
