### ISSUE TITLE
failed to "StartContainer" for "cassandra" with CrashLoopBackOff

### ISSUE THREAD

**Issue by jukylin** [jaegertracing/jaeger-kubernetes#34]
Hi, I deploy Jager via 
> kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-kubernetes/master/production/jaeger-production-template.yml

and get errors :

![alt](https://upload.cc/i/5Vh9OT.png)

I use k8s in Mac. 

Why I've got these errors? Thinks!

**Comment by jpkrohling** [comment]
It is expected to have the collector/query pods fail for a few minutes on a "cold" deployment, as they both depend on the Cassandra cluster to be healthy and the schema job to be successful. It looks like your schema job has not finished yet (`Running` vs. `Completed`), so, that explains why the query/collector aren't in `Running` state yet.

Kubernetes will reschedule the pods and they will eventually work fine. It's a bit strange that the `cassandra-0` has terminated in error, but that might be unrelated.

Are you seeing the pods in error state even after, say, 10 minutes? If so, then that would be an issue.

**Comment by jukylin** [comment]
Yes ,23 minutes.

![alt](https://upload.cc/i/r0FeU3.png)

another once I saw all in error

**Comment by jpkrohling** [comment]
Could you try the procedure I mentioned on https://github.com/jaegertracing/jaeger-kubernetes/issues/32#issuecomment-327515820 ? If it works, then it's the same problem as reported on #32

**Comment by jukylin** [comment]
Mybe Cassandra is not working.

```
# kubectl logs jaeger-cassandra-schema-job-jz07w

Traceback (most recent call last):
  File "/usr/bin/cqlsh.py", line 2428, in <module>
    main(*read_options(sys.argv[1:], os.environ))
  File "/usr/bin/cqlsh.py", line 2407, in main
    encoding=options.encoding)
  File "/usr/bin/cqlsh.py", line 479, in __init__
    load_balancing_policy=WhiteListRoundRobinPolicy([self.hostname]),
  File "/usr/share/cassandra/lib/cassandra-driver-internal-only-3.10.zip/cassandra-driver-3.10/cassandra/policies.py", line 417, in __init__
socket.gaierror: [Errno -2] Name or service not known
Cassandra is still not up at cassandra. Waiting 1 second.

```

The command (`kubectl logs job/jaeger-cassandra-schema-job`) not work
```
error: cannot get the logs from batch/__internal, Kind=Job
```

**Comment by jpkrohling** [comment]
The first is "expected", if it's about the same issue as #32 , but to confirm, could you run the following commands:

```
kubectl delete job/jaeger-cassandra-schema-job
kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-kubernetes/master/production/jaeger-production-template.yml
```

**Comment by jpkrohling** [comment]
If this is still happening, please reopen.
