### ISSUE TITLE
How can jaeger-client talk to agent running as Kubernetes service?

### ISSUE THREAD

**Issue by bharat-p** [jaegertracing/jaeger-kubernetes#4]
Its more of a question than an issue. I am new to Kubernetes and trying to understand how does this deployment work? given the fact that "jaeger-client" expects agent to be running on localhost?

So if I have a web service running as a pod, how will jaeger client in that service will connect to jaeger agent running as part of `jaeger-all-in-one` service?

**Comment by pavolloffay** [comment]
Agent does not have to run on the same pod. Host in the sender can be configured. Which client are you using?

In k8s you just point sender to `jaeger-all-in-one` or the name of the Jaeger service.

**Comment by bharat-p** [comment]
Thank you for your reply @pavolloffay . I am using `jaeger-client-python` and it has agent endpoint address fixed to `localhost`. https://github.com/uber/jaeger-client-python/blob/master/jaeger_client/config.py#L298.
There was this PR opened: https://github.com/uber/jaeger-client-python/pull/49 to make agent host config configurable, but it was suggested that it might not be needed as it might work as is in k8s and thats why I wanted to check how does this work, without changing agent host config in client.
