### ISSUE TITLE
Rename service/deployment etc to remove 'all-in-one'

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-kubernetes#5]
The Service and Deployment metadata names are currently 'jaeger-all-in-one' and 'jaeger-all-in-one-agent'.

This means that when being used by an application, the application's configuration would need to use the 'all-in-one' to reference the target (e.g. agent). So when switching to a 'production' version of the jaeger deployment, the applications would need to be changed.

Wondering if it would be better to use a consistent set of names, across the all-in-one and production templates, so that the applications/configurations are not impacted by a change - i.e. it is simply an administration issue whether the all-in-one or production templates have been deployed.

**Comment by pavolloffay** [comment]
+1, I think we have already introduced this consistency in openshift repo. The same e2e tests should be run on development and production templates to verify this.

**Comment by pavolloffay** [comment]
fixed in https://github.com/jaegertracing/jaeger-kubernetes/pull/9/
