### ISSUE TITLE
Could not find aggregation of distinct_services

### ISSUE THREAD

**Issue by fatg1988** [jaegertracing/jaeger-kubernetes#52]
how can i do ~~~~
deploy jaeger-production-template-with-elasticsearch.yml
k8s version 1.6.4

jaeger-query
curl 10.254.100.41/api/services
{"data":null,"total":0,"limit":0,"offset":0,"errors":[{"code":500,"msg":"Could not find aggregation of distinct_services"}]}

jaeger-collector logs
` {"level":"info","ts":1508414827.1502573,"caller":"healthcheck/handler.go:46","msg":"Health Check server started","http-port":14269}
{"level":"info","ts":1508414828.176905,"caller":"collector/main.go:113","msg":"Starting Jaeger Collector HTTP server","http-port":14268}
{"level":"info","ts":1508414828.176981,"caller":"healthcheck/handler.go:88","msg":"Health Check state change","http-status":204}
{"level":"info","ts":1508414828.1772332,"caller":"collector/main.go:154","msg":"Listening for Zipkin HTTP traffic","zipkin.http-port":9411} `

jaeger-query logs 
` {"level":"info","ts":1508414826.0206602,"caller":"healthcheck/handler.go:46","msg":"Health Check server started","http-port":16687}
{"level":"info","ts":1508414828.0497098,"caller":"healthcheck/handler.go:88","msg":"Health Check state change","http-status":204}
{"level":"info","ts":1508414828.049764,"caller":"query/main.go:92","msg":"Starting jaeger-query HTTP server","port":16686} `

jaeger-agent logs
` {"level":"info","ts":1508415421.4560003,"caller":"tchannel/bulider.go:89","msg":"Enabling service discovery","service":"jaeger-collector"}
{"level":"info","ts":1508415421.4561126,"caller":"peerlistmgr/peer_list_mgr.go:111","msg":"Registering active peer","peer":"jaeger-collector.default.svc:14267"}
{"level":"info","ts":1508415421.4566708,"caller":"agent/main.go:53","msg":"Starting agent"}
{"level":"info","ts":1508415422.4564009,"caller":"peerlistmgr/peer_list_mgr.go:159","msg":"Not enough connected peers","connected":0,"required":1}
{"level":"info","ts":1508415422.4564948,"caller":"peerlistmgr/peer_list_mgr.go:166","msg":"Trying to connect to peer","host:port":"jaeger-collector.default.svc:14267"}
{"level":"info","ts":1508415422.4603477,"caller":"peerlistmgr/peer_list_mgr.go:176","msg":"Connected to peer","host:port":"0.0.0.0:14267"} `

**Comment by pavolloffay** [comment]
@fatg1988 hi, 

try to report some data to the server. The error message should disappear then.

I think it's this issue https://github.com/jaegertracing/jaeger/issues/464

**Comment by fatg1988** [comment]
how to report data?
i visit my svc  my-nginx several times , but not work.

![default](https://user-images.githubusercontent.com/3365952/31819733-7e75d8a0-b5d0-11e7-9a1d-9a16564885f3.png)

` 172.254.91.1 - - [20/Oct/2017:11:32:00 +0000] "GET /nginx/index.html HTTP/1.1" 404 169 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101 Firefox/56.0" "10.236.65.75"
172.254.91.1 - - [20/Oct/2017:11:45:47 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101 Firefox/56.0" "10.236.65.75"
172.254.91.1 - - [20/Oct/2017:11:45:48 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101 Firefox/56.0" "10.236.65.75"
172.254.91.1 - - [20/Oct/2017:11:45:48 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101 Firefox/56.0" "10.236.65.75"
172.254.91.1 - - [20/Oct/2017:11:45:48 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101 Firefox/56.0" "10.236.65.75" `

**Comment by joway** [comment]
+1 

@pavolloffay Do you have any update about this bug ?

**Comment by pavolloffay** [comment]
Closing it's been fixed in jaeger.
