### ISSUE TITLE
Mention Helm support in README

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-kubernetes#55]
https://github.com/kubernetes/charts/tree/master/incubator/jaeger

**Comment by jpkrohling** [comment]
I love that helm template and I've been playing with it for a couple days now. @dvonthenen mentioned that he's almost ready with the Elasticsearch changes, so, it will be on par with this repository.

I'd just like to make sure we mention that the two options are not "the same thing", at least not yet.

**Comment by dvonthenen** [comment]
The PR has been merged. Will have the update to the Jaeger chart to support ES as a backend.

**Comment by dvonthenen** [comment]
Running into issues with the ES chart. The client nodes seem to be failing due to health check issues. I have reached out to the chart maintainers for help.

**Comment by dvonthenen** [comment]
I have a PR open for supporting using an external Cassandra or ElasticSearch backing store. https://github.com/kubernetes/charts/pull/2684

**Comment by objectiser** [comment]
Closed by #65
