### ISSUE TITLE
Stand-alone Agent sidecar by NodePort

### ISSUE THREAD

**Issue by xiaosefengyun** [jaegertracing/jaeger-kubernetes#60]
I want to expose the agent port, so that other external applications can access and write jaegertracing log, can?

**Comment by pavolloffay** [comment]
hi @xiaosefengyun, we currently do not provide resource files for this configuration, agent should be deployed as a sidecar in each pod. 

In the git history you can find that we were deploying agent as `DaemonSet` so the same address could be used to configure sender.
https://github.com/jaegertracing/jaeger-kubernetes/blob/b0b6ef2f941847f1dbfc7cf9b42d5ac9260d30b7/production/jaeger-production-template.yml#L232

Note that you can also http sender and send spans directly to jaeger-collector.

**Comment by jpkrohling** [comment]
As we haven't heard back in a while, I'm closing this issue.
