### ISSUE TITLE
Production config

### ISSUE THREAD

**Issue by 23doors** [jaegertracing/jaeger-kubernetes#7]
Any plans to add production yamls similar to: https://github.com/jaegertracing/jaeger-openshift ? Currently all-in-one isn't really suitable for it.

**Comment by jpkrohling** [comment]
Yes, I do have plans to do that, but I'm currently working on other tasks. It shouldn't be hard to adapt the OpenShift one to work for plain Kubernetes, though. Would be a nice contribution ;)

**Comment by pavolloffay** [comment]
closed via https://github.com/jaegertracing/jaeger-kubernetes/pull/8
