### ISSUE TITLE
Authorized access to UI

### ISSUE THREAD

**Issue by maxkondr** [jaegertracing/jaeger-kubernetes#82]
Hello,

I haven't found any option related to authorization. Is it possible to protect access to UI with login/passwd?
Depending on application it is possible that some sensitive data can be dumped into spans and it is strictly desirable to protect such data.

**Comment by jpkrohling** [comment]
There were some discussions around this in the past and the current consensus is that this is better handled via a sidecar. The general approach with a concrete example was the target of a blog post[1], and I do have a task in my queue to check if it's still up to date.

If you think the sidecar approach is not appropriate, please do check the mailing list threads on this topic and feel free to start a new one if there's an aspect that hasn't been discussed yet.

1 - http://www.hawkular.org/blog/2017/07/jaeger-with-security-proxy.html
