### ISSUE TITLE
Jaeger should use healthcheck for readinessProbe

### ISSUE THREAD

**Issue by eundoosong** [jaegertracing/jaeger-kubernetes#86]
Query and standalone currently have readinessProbe using Query port(16686).

Wouldn't it be better using healthcheck port for all components(Collector, Query, Standalone)?
They have their own port for healthcheck. 
(Note that Standalone healthcheck is in  [PR](https://github.com/jaegertracing/jaeger/pull/784))

Another question, 
Per my understanding, there are 2 probes in kubernetes. livenessProbe and readinessProbe.
Why readinessProbe is used?

**Comment by jpkrohling** [comment]
> Wouldn't it be better using healthcheck port for all components(Collector, Query, Standalone)?

Absolutely. A PR would be welcomed :)

>  Why readinessProbe is used?

The health check isn't actually checking the health of the component. Instead, we are using it mostly as a "readiness probe", to mark when the component is ready to receive requests (ie: when it has connected to the backend storage/services).

**Comment by eundoosong** [comment]
Thanks for the clarification.
I'll look into this for kubernetes and openshfit, will PR.

**Comment by jpkrohling** [comment]
v1.6 has just been published. Is this the right time to work on this issue?

**Comment by eundoosong** [comment]
Ok, I'll work on this.
