### ISSUE TITLE
Pinned Image Versions

### ISSUE THREAD

**Issue by Aergonus** [jaegertracing/jaeger-kubernetes#88]
The deployment versions are lagging behind the released versions three months now. Is there a reason they're pinned to 1.2

**Comment by jpkrohling** [comment]
No, feel free to submit a PR with the new versions :)

**Comment by Spellchaser** [comment]
It doesn't seem like a very good/maintainable policy. I'll update the docs too, to specify that new users should check the latest jaeger release version.

I bring this up because the official docs have moved to using `query.base-path` rather than `query.prefix` that's pre 1.3
