### ISSUE TITLE
Agent ports

### ISSUE THREAD

**Issue by Spellchaser** [jaegertracing/jaeger-kubernetes#91]
https://www.jaegertracing.io/docs/deployment/#agent
The yamls are missing the new http port
          - containerPort: 5778
            protocol: TCP

**Comment by jpkrohling** [comment]
Would you be interested in sending a PR with the fix?

**Comment by Spellchaser** [comment]
Yeah just later when I manage to finish some high priority items

**Comment by Spellchaser** [comment]
Voila! Merged
